name: Deploy React App to S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # 프로젝트에 맞는 Node.js 버전

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. React 애플리케이션 빌드
      - name: Build project
        run: npm run build

      # 5. 빌드 결과물을 S3에 업로드
      - name: Sync to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
        run: |
          aws s3 sync ./build s3://mytestcicd --delete
          # ./build: React 앱 빌드 결과물 디렉토리
      
      - name: Notify Slack on Success
        if: success()  # 성공 시 실행
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"✅ Build Succeeded for ${{ github.repository }} on branch ${{ github.ref }}.\"}" ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on Failure
        if: failure()  # 실패 시 실행
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"❌ Build Failed for ${{ github.repository }} on branch ${{ github.ref }}.\"}" ${{ secrets.SLACK_WEBHOOK_URL }}

